server:
  port: ${SERVER_PORT:8088}
  servlet:
    context-path: /snail-job

spring:
  application:
    name: snail-job
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: off
  profiles:
    active: ${PROFILE:dev}
  datasource:
    name: snail_job
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: jdbc:${DATASOURCE_PLATFORM:postgresql}://${DATASOURCE_HOST:postgresql}:${DATASOURCE_PORT:5432}/${DATASOURCE_DATABASE:snail_job}?${DATASOURCE_PARAM:tcpKeepAlive=true&reWriteBatchedInserts=true&ApplicationName=snail-job&useSSL=false&reWriteBatchedInserts=true&stringtype=unspecified}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:laokou123}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 180000
      minimum-idle: 5
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 180000
      pool-name: snail_job
      max-lifetime: 1800000
  web:
    resources:
      static-locations: classpath:admin/

mybatis-plus:
  typeAliasesPackage: com.aizuda.snailjob.template.datasource.persistence.po
  global-config:
    db-config:
      where-strategy: NOT_EMPTY
      capital-mode: false
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

logging:
  config: classpath:logback-boot.xml

snail-job:
  retry-pull-page-size: 1000 # 拉取重试数据的每批次的大小
  job-pull-page-size: 1000 # 拉取重试数据的每批次的大小
  server-port: 17888  # 服务器端口
  log-storage: 7 # 日志保存时间(单位: day)
  rpc-type: grpc
